services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-home:/var/jenkins-home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "988"  # Replace with your host Docker group ID
      # To get the ID use:
      # getent group docker

volumes:
  jenkins-home:
